version: 2.1

orbs:
  cypress: cypress-io/cypress@3
  jest: circleci/jest@2 # You may need to adjust the version based on the available versions

jobs:
  jest-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run Jest tests
          command: yarn unit

workflows:
  version: 2
  test:
    jobs:
      - cypress/run:
          package-manager: "yarn"
          start-command: "yarn start"
      - jest-tests: # Include the Jest tests job in your workflow
